/**
 * Gets a random multiplication, division, subtraction, or addition question
 * 
 * @returns {object} The randomly generated math question and the correct answer
 */
function getQuestion() {
    const operations = ["-", "+", "*", "/"];
    const num1 = Math.floor(Math.random() * 20) + 1;
    const num2 = Math.floor(Math.random() * 20) + 1;
    const operation = operations[Math.floor(Math.random() * operations.length)];
    let question = "";
    let answer = 0;

    switch (operation) {
        case "+":
            question = `What is ${num1} + ${num2}?`;
            answer = num1 + num2;
            break;
        case "-":
            question = `What is ${num1} - ${num2}?`;
            answer = num1 - num2;
            break;
        case "*":
            question = `What is ${num1} x ${num2}?`;
            answer = num1 * num2;
            break;
        case "/":
            const product = num1 * num2;
            question = `What is ${product} / ${num2}?`;  // Avoiding fractions by calculating the product first
            answer = num1;  // Answer is num1 after dividing the product by num2
            break;
    }
    return { question, answer };
}

/**
 * Parses the provided question and checks if the provided answer is correct
 * 
 * @param {object} questionObject The question object generated by getQuestion
 * @param {number|string} userAnswer The user's submitted answer
 * @returns {boolean} True if the answer was correct, false otherwise
 */
function isCorrectAnswer(questionObject, userAnswer) {
    // Ensure both userAnswer and the correct answer are numbers for comparison
    return Number(userAnswer) === questionObject.answer;
}

module.exports = {
    getQuestion,
    isCorrectAnswer
};